#MySQL配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    type:
  redis:
    database: 0
    password: 123@456
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        min-idle: 0
    host: localhost
  cache:
    cache-names: c1,c2,c3,c4,c5
    redis:
      time-to-live: 180
  mail:
    host: smtp.qq.com
    port: 465
    username: 840679158@qq.com
    password: america_kitten
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          socketFacotry:
            class: javax.net.ssl.SSLSocketFactory
        debug: true
  servlet:
    multipart:
      enabled: true
mybatis:
  config-location: classpath:/mybatis-config.xml
server:
  port: 8082
